version: '3.8'

services:
  n8n-google-ai-dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5678:5678"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin
    command: npm run dev
    
  n8n-google-ai-prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5678:5678"
    environment:
      - NODE_ENV=production
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin
    command: npm start
